name: Dev server deploying
on:
  push:
    branches:
     - master
jobs:
  preparing:
    runs-on: ubuntu-latest
    steps:
      - name: Get repository code
        uses: actions/checkout@v3
      - name: Dependencies installing
        run: npm ci
      - name: Build project
        run: npm run build
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          path: dist
          name: dist-files
      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: dist-files
  deploy:
    runs-on: ubuntu-latest
    needs: preparing
    steps:
      - name: Deploy on dev server
        run: echo "Deployment process running ..."
