name: Build and deploy to dev server

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v3
      - name: Install dependencies
        run: npm install
      - name: Build
        run: npm run build-only
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          path: dist
          name: dist

      - name: Deploy to server
        uses: easingthemes/ssh-deploy@v4.1.10
        env:
          SSH_PRIVATE_KEY: ${{ secrets.GH_SSH_PRIVATE_KEY }}
          SOURCE: "dist"
          REMOTE_HOST: "99.192.222.110"
          REMOTE_USER: "githubactions"
          SSH_CMD_ARGS: "-v"